### PR TITLE
use mingw revision

### PR DESCRIPTION
**Pull request by ericLemanissier**
PLEASE DON'T MERGE THIS YET !

a test is in porgress on my fork: https://github.com/ericLemanissier/mingw-builds-binaries/runs/4761121396?check_suite_focus=true

CC @cristianadam

We could also put the rt version in the tag, WDYT ?

### CODE REVIEW

**Comment by niXman** [comment]
> We could also put the rt version in the tag, WDYT ?

this is amazing!

**Comment by cristianadam** [comment]
Currently the artifact name looks like: `x86_64-11.2.0-release-posix-seh-rt_v9-rev0.7z` which would suggest a tag like:

`11.2.0-rt_v9-rev1` or `11.2.0-rt_trunk-rev0`. I personally like having the `v` as part of the version `v11.2.0-rt_v9-rev0`.

But, it's not that important. I'm fine with any version scheme 😄

**Comment by niXman** [comment]
> 11.2.0-rt_v9-rev1 or 11.2.0-rt_trunk-rev0

ah, you are right!

**Comment by ericLemanissier** [comment]
tests are in porgress in:

- https://github.com/ericLemanissier/mingw-builds-binaries/actions/runs/1678366760
- https://github.com/ericLemanissier/mingw-builds-binaries/actions/runs/1678366770

**Comment by ericLemanissier** [comment]
It looks like it worked!

**Comment by ericLemanissier** [comment]
Well, actually the artifacts of rt_trunk release have rt_v9. There is something wrong

**Comment by ericLemanissier** [comment]
well, actually (bis) it seems ok (?) artiacts on https://github.com/ericLemanissier/mingw-builds-binaries/releases/tag/11.2.0-rt_trunk-rev0 are the same as https://github.com/cristianadam/mingw-builds/releases/tag/v11.2.0-rev1, and different from https://github.com/ericLemanissier/mingw-builds-binaries/releases/tag/11.2.0-rt_v9-rev0

**Comment by niXman** [comment]
sorry, but I'm not sure I understood you correctly...

> actually the artifacts of rt_trunk release have rt_v9.

but that should not be the case. or is it already fixed?
will check now too.

**Comment by ericLemanissier** [comment]
The build script seems to generate an archive which has rt_v9 in its name, even if rt_trunk was asked. The proper rt seems to be used anyway, based on the build log.

**Comment by niXman** [comment]
is this happening because of the github actions script?
or because of mingw-builds?

**Comment by ericLemanissier** [comment]
it's because of the mingw-builds 's build scripts: see how `--rt-version=trunk` is passed here: https://github.com/ericLemanissier/mingw-builds-binaries/runs/4764630918?check_suite_focus=true#step:4:1 and yet it builds `x86_64-11.2.0-multilib-posix-sjlj-rt_v9-rev0` : https://github.com/ericLemanissier/mingw-builds-binaries/runs/4764630918?check_suite_focus=true#step:4:191

**Comment by niXman** [comment]
got it, will fix it.

thank you very much guys! @ericLemanissier @cristianadam

**Pull request merged**
