### PR TITLE
create github action building tags

### PR DESCRIPTION
**Pull request by ericLemanissier**
cc @cristianadam 

I'm currently testing these script with 11.2.0 tag on https://github.com/ericLemanissier/mingw-builds-binaries/actions/runs/1673635393

### CODE REVIEW

**Comment by cristianadam** [comment]
Cool, and thank you!

For Qt we need to have `--rt-version=master` since `v9` doesn't have the multimedia header changes that Qt Multimedia needs.

Hopefully `v10` will come soon enough and this won't be a problem anymore. https://www.mingw-w64.org/changelog/ seems to release yearly,

**Comment by niXman** [comment]
@ericLemanissier looks like we have some trouble with github-actions because the error: bad mode. Script gcc-v11.2.0-rev0.sh not found. terminate.

**Comment by niXman** [comment]
> gcc-v11.2.0-rev0.sh

it should be `gcc-11.2.0.sh` (ie without `v` and without `-rev0`)

**Comment by ericLemanissier** [comment]
Yeah, the tag must be `11.2.0` I don't know yet if we can do better

**Comment by niXman** [comment]
> Noob question: What does the "rev" reference, mingw or gcc?

this is necessary in order to be able to build the same version of GCC several times, but, for example, with different patches or with different flags.
but this requires the ability to specify the revision of the build in tags :(

**Comment by ericLemanissier** [comment]
ok, I'll work on my fork to make it split the tag into gcc version and mingw revision, and properly forward this information to build scripts.

**Pull request merged**
