### PR TITLE
GitHub Actions: Use C drive for buildroot

### PR DESCRIPTION
**Pull request by ericLemanissier**
same change as https://github.com/niXman/mingw-builds/pull/594

### CODE REVIEW

**Comment by cristianadam** [comment]
This would require a `12.1.0-rt_v10-rev3` so that the PR is taken into consideration. Might need to do a retry if some jobs do not complete under 6 hours.

**Comment by ericLemanissier** [comment]
@niXman Is it possible to create a new `12.1.0-rt_v10-rev3` tag , cf @cristianadam's message above

**Comment by niXman** [comment]
done: https://github.com/niXman/mingw-builds-binaries/releases/tag/12.1.0-rt_v10-rev3

**Comment by ericLemanissier** [comment]
@niXman unfortunately we hit the time limit for one job. can you simply restart the (i686, posix, sjlj) https://github.com/niXman/mingw-builds-binaries/runs/6792095437?check_suite_focus=true ? It should not be needed to create a new tag

**Comment by niXman** [comment]
done

**Pull request merged**
